# Generated by Django 4.2.13 on 2024-05-27 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cook',
            old_name='User',
            new_name='user',
        ),
    ]
