# Generated by Django 4.2.13 on 2024-05-27 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_user_cook_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cook',
            old_name='user',
            new_name='title',
        ),
    ]
