# Generated by Django 4.2.13 on 2024-06-06 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipestep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='body',
        ),
    ]
