# Generated by Django 4.2.13 on 2024-06-15 21:28

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('recipes', '0005_alter_recipe_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=20,
                                      validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
