# Generated by Django 4.2.13 on 2024-06-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('recipes', '0006_alter_recipeingredient_quantity'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(fields=('title', 'author'), name='unique_migration_host_combination'),
        ),
    ]
