# Generated by Django 4.2.13 on 2024-06-02 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_ingredient_description_recipe_ingredient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='teams',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(to='recipes.ingredient'),
        ),
        migrations.DeleteModel(
            name='Recipe_Ingredient',
        ),
    ]
