# Generated by Django 4.2.13 on 2024-06-21 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_alter_recipestep_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='people',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
